### PR TITLE
Rename main_test.go for slices4 in info.toml

### PR DESCRIPTION
**Pull request by joshaustintech**
When I get to this exercise and do `golings run next` it says the file isn't found.

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Thank you for contributing @joshaustintech 
Actually, the name of the file is correct. The problem here is that the exercise in the `info.toml` file should be renamed to `main_test.go`
Do you mind to fix it there?

**Comment by joshaustintech** [comment]
I'd be happy to later today 😎

**Comment by mauricioabreu** [comment]
Thank you @joshaustintech 
feel free to ask for help

**Comment by joshaustintech** [comment]
Ready for your review, @mauricioabreu 😎

**Comment by mauricioabreu** [comment]
Thank you @joshaustintech merged!

**Pull request merged**
